### ISSUE TITLE
Incompatible script command for opening the browser.

### ISSUE THREAD

**Issue by MahirMahdi** [FrigadeHQ/frigade-react-nextjs-demo#1]
The current script command: `"open-browser": "open https://localhost:5678"` is not a standard command on Windows or Linux.

![Screenshot 2023-07-29 011226](https://github.com/FrigadeHQ/frigade-react-nextjs-demo/assets/66949598/becc80f9-765a-4384-8479-e9f641ca0f1c)

I believe it's necessary to make sure the script command is compatible across different OS so that developers can have a smooth experience and focus on solving problems.

I came up with two solutions
. One is to make it a single line command like this: `"open-browser": "node -e \"const { execFile } = require('child_process'); /^win/.test(process.platform) ? execFile('cmd', ['/c', 'start', 'https://localhost:5678']) : execFile('xdg-open', ['https://localhost:5678'])\""`, which makes it harder to read. 

Another solution would be to add a function like this in `server.js`:

` const { execFile } = require('child_process');`

`function openBrowser(url) {
  if (/^win/.test(process.platform)) {
    execFile('cmd', ['/c', 'start', url]);
  } else {
    execFile('xdg-open', [url]);
  }
}`

`openBrowser('https://localhost:5678');`, 

and then just run the script like this: `"dev": "yarn node server.js"`, which makes it more maintainable and readable.

**Comment by christianmat** [comment]
Hey @mahirmahdi, thanks for brining this to our attention. Feel free to open a PR with above change.

**Comment by MahirMahdi** [comment]
> Hey @MahirMahdi, thanks for brining this to our attention. Feel free to open a PR with above change.

Anytime😀.

Sure. On it.

**Comment by dfltr** [comment]
Fixed in 5f1c02b -- thanks again for catching this issue!
