### ISSUE TITLE
Request to include config.yaml in git repo

### ISSUE THREAD

**Issue by gardner** [FrigadeHQ/frigade-react-nextjs-demo#4]
Hi there, 

I am just learning about Frigade and am trying to understand how the frontend interacts with the service. It could be helpful to include the `config.yaml` in the git repo so that developers can reference it when understanding the flows.

Thanks

**Comment by christianmat** [comment]
That's a great suggestion. Just added them in the `example-configs` folder here: https://github.com/FrigadeHQ/frigade-react-nextjs-demo/tree/main/example-configs

Let us know if you have any other suggestions for making the demo more useful 👍
